# A Quick Primer on Numpy

> Why do we need numpy?

- Python loops are slow

- Basic Python data structures were not designed for fast matrix operations

- Python allocates memory dynamically, which is not efficient when we know the amount of variables we're gonna be working with

### Array Initialization

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])   # Create a rank 1 array

In [3]:
type(a)            # Prints "<class 'numpy.ndarray'>"

numpy.ndarray

In [4]:
a.shape            # Prints "(3,)"

(3,)

In [5]:
print(a[0], a[1], a[2])   # Prints "1 2 3"

1 2 3


In [6]:
a[0] = 5                  # Change an element of the array

In [7]:
a

array([5, 2, 3])

In [8]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [9]:
b.shape

(2, 3)

In [10]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
print(b[0, 0], b[0, 1], b[1, 0])   # Prints "1 2 4"

1 2 4


### Functions for creating arrays

In [11]:
a = np.zeros((2,2))   # Create an array of all zeros

In [12]:
a

array([[0., 0.],
       [0., 0.]])

In [13]:
b = np.ones((1,2))    # Create an array of all ones

In [23]:
b

array([[1., 1.]])

In [14]:
c = np.full((2,2), 7)  # Create a constant array

In [15]:
c

array([[7, 7],
       [7, 7]])

In [19]:
d = np.eye(5)         # Create a 2x2 identity matrix

In [20]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
e = np.random.random((2,2))  # Create an array filled with random values

In [22]:
e

array([[0.43314627, 0.04066004],
       [0.06984818, 0.64124408]])

### Array Indexing

In [23]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [25]:
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
b = a[:2, 1:3]

In [26]:
b

array([[2, 3],
       [6, 7]])

In [27]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0, 1])   # Prints "2"
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])   # Prints "77"

2
77


In [28]:
a

array([[ 1, 77,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# Two ways of accessing the data in the middle row of the array.
# Mixing integer indexing with slices yields an array of lower rank,
# while using only slices yields an array of the same rank as the
# original array:
row_r1 = a[1, :]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)


In [30]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print(col_r2, col_r2.shape)  # Prints "[[ 2]
                             #          [ 6]
                             #          [10]] (3, 1)"

[77  6 10] (3,)
[[77]
 [ 6]
 [10]] (3, 1)


> When you index into numpy arrays using slicing, the resulting array view will always be a subarray of the original array. 

> In contrast, integer array indexing allows you to construct arbitrary arrays using the data from another array

In [31]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [32]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [44]:
# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[1 4 5]


In [33]:
# The above example of integer array indexing is equivalent to this:
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))  # Prints "[1 4 5]"

[1 4 5]


In [34]:
# When using integer array indexing, you can reuse the same
# element from the source array:
print(a[[0, 0], [1, 1]])  # Prints "[2 2]"

[2 2]


In [48]:
# Equivalent to the previous integer array indexing example
print(np.array([a[0, 1], a[0, 1]]))  # Prints "[2 2]"

[2 2]


One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [35]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

In [36]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
s1 = np.array([0, 1, 3])
s2 = np.array([0, 2, 1])

In [38]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
a[s1,s2]

array([ 1,  6, 11])

In [78]:
a

array([[ 6,  2,  3],
       [ 4,  5, 11],
       [ 7,  8,  9],
       [10, 16, 12]])

In [41]:
a[s1,s2] += 5

In [42]:
a

array([[ 6,  2,  3],
       [ 4,  5, 11],
       [ 7,  8,  9],
       [10, 16, 12]])

Boolean array indexing: Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition.

In [43]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [44]:
(a > 2)

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [45]:
a[a > 2]

array([3, 4, 5, 6])

### Datatypes

In [47]:
x = np.array([1, 2])   # Let numpy choose the datatype
print(x.dtype)         

x = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(x.dtype)             # Prints "float64"

x = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(x.dtype)                         # Prints "int64"

int32
float64
int64


### Array math

In [48]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [49]:
x,y

(array([[1., 2.],
        [3., 4.]]),
 array([[5., 6.],
        [7., 8.]]))

In [47]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [50]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [51]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [52]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [53]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [54]:
x = np.array([[1,2],[3,4]], dtype=np.float64)

In [55]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [56]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [57]:
v,w

(array([ 9, 10]), array([11, 12]))

In [58]:
print(v.dot(w))
print(np.dot(v, w))

219
219


In [100]:
x,v

(array([[1, 2],
        [3, 4]]),
 array([ 9, 10]))

In [101]:
print(x.dot(v))
print(np.dot(x, v))

[29 67]
[29 67]


In [59]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [60]:
print(x.dot(y))
print(np.dot(x, y))

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [61]:
x = np.array([[1,2],[3,4]])

In [62]:
x

array([[1, 2],
       [3, 4]])

In [63]:
print(np.sum(x))  # Compute sum of all elements; prints "10"

10


In [64]:
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"

[4 6]


In [65]:
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

[3 7]


In [66]:
x = np.array([[1,2], [3,4]])

In [67]:
x

array([[1, 2],
       [3, 4]])

In [68]:
x.T

array([[1, 3],
       [2, 4]])

# Broadcasting

In [69]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

In [70]:
# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

In [71]:
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [74]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [75]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [76]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
